name = "collaborate-worker"
compatibility_date = "2025-08-24"
main = "src/index.ts"

# Environment variables
[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19LN2czeE43UzViNlc5cW5FbGlPTVoiLCJhcGlfa2V5IjoiMDFLM05UNjlRVEY1TTMyRFZUWUVBRTE3RFciLCJ0ZW5hbnRfaWQiOiJmNGJlZDkyYWNjZGYyNDMxZjFiNTM3MjMzNWYwMTkxZmRhZmIzMzBmZDEwYjU0Njg0M2Q3MWM1M2NkMzE1ZGY3IiwiaW50ZXJuYWxfc2VjcmV0IjoiYTI1NDAxNGItYzQxYy00MzAyLTlmMDEtM2Y0MWZkNTY4NThmIn0.v3Alqzx57_petm_9DxyDTYCUv3wJ-mSjAt-AP2sRssY"
JWT_SECRET = "replace-me-in-prod"
