name = "collaborate-worker"
compatibility_date = "2025-08-24"
main = "src/index.ts"
[vars]
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19sQWQzNkVnR004WlRLWTJVREJXbHgiLCJhcGlfa2V5IjoiMDFLM0VBUkQ5RkgxQjVLRDJKRlRBWDVKS1kiLCJ0ZW5hbnRfaWQiOiI1ZDU3ZDM0YjVmNDE2Y2JlYWZhM2E5YTM5YTU1ZjhlODNjNWYwNGMzNTAwNDJkZmQwZTJhMjhlMzgyNGRmYTAxIiwiaW50ZXJuYWxfc2VjcmV0IjoiYmI3YTNiMWUtYWEyOC00NWMzLWIyNWUtNzcwZDYyOWI0N2RjIn0.jWDhnS4pSfbSHKLBl25WHXX9ctzMacNXlF9ZWgjuYxw"
JWT_SECRET = "your-super-secret-jwt-key"
