name = "collaborate-worker"
compatibility_date = "2025-08-24"
main = "src/index.ts"

# Environment variables
[vars]
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza192UHY4a0dhVFNENWNkLTZZV2pUOVUiLCJhcGlfa2V5IjoiMDFLM1AxN1Y2REpaUTNQMFRLRUFQMlMyTlkiLCJ0ZW5hbnRfaWQiOiIzYjA0NGI1OWM0ZjE3MzhhMTNiNDc1N2EwNDdkZjk2YzU4ODA3MDM0M2M2M2I1ZjViMGFkMTZhNTJlYWQ1ZjY1IiwiaW50ZXJuYWxfc2VjcmV0IjoiZTk3NDliMTEtMTE4MS00MzBlLTkwZWItOGFhMWQxNjQyM2U1In0.3ci-FzJZhuNNn4bSH3RA06YtCsy3xI0W5Jlgxg_y50w"
JWT_SECRET = "replace-me-in-prod"
