name = "collaborate-worker"
compatibility_date = "2025-08-24"
main = "src/index.ts"

# Environment variables
[vars]
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19rMHJXQ2FLM2RTS2d4eW5uZHk1R3UiLCJhcGlfa2V5IjoiMDFLM1Q2VlFFV0FYSk0zVk42NVJSWlpQQTYiLCJ0ZW5hbnRfaWQiOiJlMjU4YzYyMWJhODhmZTA2Yzk0YWQwYzU5Mjk5NTFlZTJjMGE2OTg5YjI1YzlmNTk3NWUwMjI4Yzg4ZTZhZTdmIiwiaW50ZXJuYWxfc2VjcmV0IjoiMDc2NTA3YjktNjlmMy00NDRiLTgzOTAtZGU0YWRiYzA0NjFlIn0.f9QQGxOhVJRxPRnwa3Ia8Gn5zJOAkoDS5yE1C0jZgMI"
JWT_SECRET = "replace-me-in-prod"
